<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReservationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('reservations')->insert([
            // Wednesday 12:00:00
            ['id' => 1,
                'date' => '2024-06-12',
                'time_slot' => '12:00:00 - 14:00:00',
                'number_of_person' => 5,
                'comment' => '',
                'customer_name' => 'Alice Johnson',
                'customer_phone_number' => '0478/123456',
                'customer_email' => 'alice.johnson@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],
            ['id' => 2,
                'date' => '2024-06-26',
                'time_slot' => '12:00:00 - 14:00:00',
                'number_of_person' => 10,
                'comment' => '',
                'customer_name' => 'Bob Smith',
                'customer_phone_number' => '0478/654321',
                'customer_email' => 'bob.smith@gmail.com',
                'active' => true,
                'is_four_course' => false,
                'is_new' => true,
            ],
            ['id' => 3,
                'date' => '2024-06-05',
                'time_slot' => '12:00:00 - 14:00:00',
                'number_of_person' => 5,
                'comment' => '',
                'customer_name' => 'Charlie Brown',
                'customer_phone_number' => '0478/987654',
                'customer_email' => 'charlie.brown@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],

            // Friday 18:00:00
            ['id' => 4,
                'date' => '2024-06-14',
                'time_slot' => '18:00:00 - 20:00:00',
                'number_of_person' => 6,
                'comment' => '',
                'customer_name' => 'David Green',
                'customer_phone_number' => '0478/111111',
                'customer_email' => 'david.green@gmail.com',
                'active' => true,
                'is_four_course' => false,
                'is_new' => false,
            ],
            ['id' => 5,
                'date' => '2024-06-07',
                'time_slot' => '18:00:00 - 20:00:00',
                'number_of_person' => 7,
                'comment' => '',
                'customer_name' => 'Eve White',
                'customer_phone_number' => '0478/222222',
                'customer_email' => 'eve.white@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],
            ['id' => 6,
                'date' => '2024-06-14',
                'time_slot' => '18:00:00 - 20:00:00',
                'number_of_person' => 7,
                'comment' => '',
                'customer_name' => 'Frank Black',
                'customer_phone_number' => '0478/333333',
                'customer_email' => 'frank.black@gmail.com',
                'active' => true,
                'is_four_course' => false,
                'is_new' => false,
            ],

            // Friday 20:00:00
            ['id' => 7,
                'date' => '2024-06-12',
                'time_slot' => '20:00:00 - 22:00:00',
                'number_of_person' => 8,
                'comment' => '',
                'customer_name' => 'Grace Blue',
                'customer_phone_number' => '0478/444444',
                'customer_email' => 'grace.blue@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],
            ['id' => 8,
                'date' => '2024-06-14',
                'time_slot' => '20:00:00 - 22:00:00',
                'number_of_person' => 6,
                'comment' => '',
                'customer_name' => 'Hank Red',
                'customer_phone_number' => '0478/555555',
                'customer_email' => 'hank.red@gmail.com',
                'active' => true,
                'is_four_course' => false,
                'is_new' => false,
            ],
            ['id' => 9,
                'date' => '2024-06-07',
                'time_slot' => '20:00:00 - 22:00:00',
                'number_of_person' => 6,
                'comment' => '',
                'customer_name' => 'Ivy Yellow',
                'customer_phone_number' => '0478/666666',
                'customer_email' => 'ivy.yellow@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],

            // Saturday 18:00:00
            ['id' => 10,
                'date' => '2024-06-19',
                'time_slot' => '12:00:00 - 14:00:00',
                'number_of_person' => 8,
                'comment' => '',
                'customer_name' => 'Jack Pink',
                'customer_phone_number' => '0478/777777',
                'customer_email' => 'jack.pink@gmail.com',
                'active' => true,
                'is_four_course' => false,
                'is_new' => false,
            ],
            ['id' => 11,
                'date' => '2024-06-15',
                'time_slot' => '18:00:00 - 20:00:00',
                'number_of_person' => 8,
                'comment' => '',
                'customer_name' => 'Kelly Orange',
                'customer_phone_number' => '0478/888888',
                'customer_email' => 'kelly.orange@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],
            ['id' => 12,
                'date' => '2024-06-21',
                'time_slot' => '18:00:00 - 20:00:00',
                'number_of_person' => 4,
                'comment' => '',
                'customer_name' => 'Leo Purple',
                'customer_phone_number' => '0478/999999',
                'customer_email' => 'leo.purple@gmail.com',
                'active' => true,
                'is_four_course' => false,
                'is_new' => true,
            ],

            // Saturday 20:00:00
            ['id' => 13,
                'date' => '2024-06-08',
                'time_slot' => '20:00:00 - 22:00:00',
                'number_of_person' => 7,
                'comment' => '',
                'customer_name' => 'Mona Brown',
                'customer_phone_number' => '0478/000000',
                'customer_email' => 'mona.brown@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],
            ['id' => 14,
                'date' => '2024-06-08',
                'time_slot' => '20:00:00 - 22:00:00',
                'number_of_person' => 7,
                'comment' => '',
                'customer_name' => 'Nina Gray',
                'customer_phone_number' => '0478/111112',
                'customer_email' => 'nina.gray@gmail.com',
                'active' => true,
                'is_four_course' => false,
                'is_new' => true,
            ],
            ['id' => 15,
                'date' => '2024-06-08',
                'time_slot' => '20:00:00 - 22:00:00',
                'number_of_person' => 6,
                'comment' => '',
                'customer_name' => 'Oscar Green',
                'customer_phone_number' => '0478/222223',
                'customer_email' => 'oscar.green@gmail.com',
                'active' => true,
                'is_four_course' => true,
                'is_new' => false,
            ],
        ]);
    }
}
